export const AUTOMATION_STATUS = {
  DESIGN: 'DESIGN',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  PROVISIONING: 'PROVISIONING',
  ACTIVE: 'ACTIVE',
  FAILED: 'FAILED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type AutomationStatus = (typeof AUTOMATION_STATUS)[keyof typeof AUTOMATION_STATUS];
